spring:
  datasource:
    url: jdbc:postgresql://192.168.1.8:5432/taskdb
    username: postgres
    password: ajay@0250A
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
