spring:
  datasource:
    url: jdbc:postgresql://taskapp-db.postgres.database.azure.com:5432/taskdb
    username: admintaskdb
    password: taskapp@2001T
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
